### PATH
export DOTFILES=~/.dotfiles
export WORKPATH=~/Workspace/
export ZSHCONFIG=~/.zsh
export ZSH=/Users/Quinoa/.oh-my-zsh
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
export VISUAL=nvim
export EDITOR=$VISUAL
eval "$(rbenv init -)"
export PYENV_ROOT="$HOME/.pyenv"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
PATH="$HOME/bin:$PATH"

### TeX
PATH="$PATH:/Library/TeX/texbin"
### tcl-tk
PATH="/usr/local/opt/tcl-tk/bin:$PATH"
### gpg
export GPG_TTY=$(tty)

### config
source $ZSHCONFIG/config.zsh


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
