# Run for login shells, before zshrc is run.

if [[ -f /usr/libexec/path_helper ]]; then
    eval `/usr/libexec/path_helper -s`
fi

# hidpi for qt5
export QT_AUTO_SCREEN_SCALE_FACTOR=1

# editor
export MANPAGER='nvim +Man!'
export MANWIDTH=80
