# Usually run for every zsh.
# editor
export VISUAL=nvim
export EDITOR=$VISUAL

export MANPAGER='nvim +Man!'

# zsh configuration files
export ZSHCONFIG=~/.zsh
export ZSH=$HOME/.oh-my-zsh

# other directories
export DOTFILES=~/.dotfiles
export WORKPATH=~/Workspace/
export PYENV_ROOT="$HOME/.pyenv"
