#!/usr/bin/env bash

if [[ ! -f /usr/local/bin/brew ]]; then
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew tap Homebrew/bundle
cd ~/.dotfiles/tools/homebrew/
brew bundle
