#!/usr/bin/env zsh

_fzf_complete_pass() {
    _fzf_complete '+m' "$@" < <(
        pwdir=${PASSWORD_STORE_DIR-~/.password-store/}
        stringsize="${#pwdir}"
        fd -t f . ~/.password-store -x echo {.} | cut -c "$((stringsize + 1))"-
    )
}

_fzf_complete_pass "$@"
