#!/usr/bin/env sh

# TODO: currently this is not useful enough

pwdir=${PASSWORD_STORE_DIR-~/.password-store/}
stringsize="${#pwdir}"
select=$(fd -t f . ~/.password-store -x echo {.} | cut -c "$((stringsize + 1))"- | fzf)
pass -c "$select"
