#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
hhkbmodmap=$HOME/.hhkbXmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap
userwallpaper=$HOME/.fehbg
usercomptonconfig=$HOME/.config/compton/compton.conf

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if (hash xinput 2>/dev/null) && (xinput | grep "HHKB" > /dev/null); then
    xmodmap $hhkbmodmap
    xinput disable 13 # touchscreen
    xinput disable 11 # cam
    xinput disable 12 # cam
elif (hash xinput 2>/dev/null) && (xinput | grep "Ultimate Gadget" > /dev/null); then
    xinput disable 14 # cam
    xinput disable 15 # cam
    xinput disable 16 # touchscreen
elif (hash xinput 2>/dev/null) && [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
    xinput disable 10 # touchscreen
    xinput disable 11 # cam
    xinput disable 12 # cam
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi


if [[ -f $userwallpaper ]] && (hash feh 2>/dev/null); then
    $userwallpaper &
fi

if [[ -f $usercomptonconfig ]] && (hash compton 2>/dev/null); then
    picom --config "$usercomptonconfig" -b
fi

if (hash fcitx5 2>/dev/null); then
    fcitx5 &
elif (hash fcitx 2>/dev/null); then
    fcitx &
fi

if (hash redshift 2>/dev/null); then
    redshift &
fi

exec xmonad
